    {/* Episode Title Lists */}
    export const episodeTitles_stevenuniverse = {
      1: [
        "Gem_Glow",
        "Laser_Light_Cannon",
        "Cheeseburger_Backpack",
        "Together_Breakfast",
        "Frybo",
        "Cat_Fingers",
        "Bubble_Buddies",
        "Serious_Steven",
        "Tiger_Millionaire",
        "Stevens_Lion",
        "Arcade_Mania",
        "Giant_Woman",
        "So_Many_Birthdays",
        "Lars_and_the_Cool_Kids",
        "Onion_Trade",
        "Steven_the_Sword_Fighter",
        "Lion_2_The_Movie",
        "Beach_Party",
        "Roses_Room",
        "Coach_Steven",
        "Joking_Victim",
        "Steven_and_the_Stevens",
        "Monster_Buddies",
        "An_Indirect_Kiss",
        "Mirror_Gem",
        "Ocean_Gem",
        "House_Guest",
        "Space_Race",
        "Secret_Team",
        "Island_Adventure",
        "Keep_Beach_City_Weird",
        "Fusion_Cuisine",
        "Garnet's_Universe",
        "Watermelon_Steven",
        "Lion_3_Straight_to_Video",
        "Warp_Tour",
        "Alone_Together",
        "The_Test",
        "Future_Vision",
        "On_the_Run",
        "Horror_Club",
        "Winter_Forecast",
        "Maximum_Capacity",
        "Marble_Madness",
        "Rose's_Scabbard",
        "The_Message",
        "Political_Power",
        "The_Return",
        "Jail_Break",
      ],
      
       2: [
        "Full_Disclosure",
        "Open_Book",
        "Joy_Ride",
        "Say_Uncle",
        "Story_For_Steven",
        "Shirt_Club",
        "Love_Letters",
        "Reformed",
        "Sworn_to_the_Sword",
        "Rising_Tides_Crashing_Skies",
        "Keeping_It_Together",
        "We_Need_to_Talk",
        "Chille_Tid",
        "Cry_for_Help",
        "Keystone_Motel",
        "Onion_Friend",
        "Historical_Friction",
        "Friend_Ship",
        "Nightmare_Hospital",
        "Sadie's_Song",
        "Catch_and_Release",
        "When_It_Rains",
        "Back_to_the_Barn",
        "Too_Far",
        "The_Answer",
        "Steven's_Birthday",
        "It_Could've_Been_Great",
        "Message_Received",
        "Log_Date_7_15_2"
      ],

      3: [
        "Super_Watermelon_Island",
        "Gem_Drill",
        "Same_Old_World",
        "Barn_Mates",
        "Hit_the_Diamond",
        "Steven_Floats",
        "Drop_Beat_Dad",
        "Mr._Greg",
        "Too_Short_to_Ride",
        "The_New_Lars",
        "Beach_City_Drift",
        "Restaurant_Wars",
        "Kiki's_Pizza_Delivery_Service",
        "Monster_Reunion",
        "Alone_at_Sea",
        "Greg_the_Babysitter",
        "Gem_Hunt",
        "Crack_the_Whip",
        "Steven_vs._Amethyst",
        "Bismuth",
        "Beta",
        "Earthlings",
        "Back_to_the_Moon",
        "Bubbled"
      ],

      4: [
        "The_Kindergarten_Kid",
        "Know_Your_Fusion",
        "Buddy's_Book",
        "Mindful_Education",
        "Future_Boy_Zoltron",
        "Last_One_Out_of_Beach_City",
        "Onion_Gang",
        "Gem_Harvest",
        "Three_Gems_and_a_Baby",
        "Steven's_Dream",
        "Adventures_in_Light_Distortion",
        "Gem_Heist",
        "The_Zoo",
        "That_Will_Be_All",
        "The_New_Crystal_Gems",
        "Storm_in_the_Room",
        "Rocknaldo",
        "Tiger_Philanthropist",
        "Room_for_Ruby",
        "Lion_4_Alternate_Ending",
        "Doug_Out",
        "The_Good_Lars",
        "Are_You_My_Dad?",
        "I_Am_My_Mom"
      ],

      5: [
        "Stuck_Together",
        "The_Trial",
        "Off_Colors",
        "Lars_Head",
        "Dewey_Wins",
        "Gemcation",
        "Raising_the_Barn",
        "Back_to_the_Kindergarten",
        "Sadie_Killer",
        "Kevin_Party",
        "Lars_of_the_Stars",
        "Jungle_Moon",
        "Your_Mother_and_Mine",
        "The_Big_Show",
        "Pool_Hopping",
        "Letters_to_Lars",
        "Cant_Go_Back",
        "A_Single_Pale_Rose",
        "Now_Were_Only_Falling_Apart",
        "Whats_Your_Problem",
        "The_Question",
        "Made_of_Honor",
        "Reunited",
        "Legs_From_Here_to_Homeworld",
        "Familiar",
        "Together_Alone",
        "Escapism",
        "Change_Your_Mind"
      ]
    };


    export const episodeTitles_overthegardenwall = {
      1: [
        "The_Old_Grist_Mill",
        "Hard_Times_at_the_Huskin_Bee",
        "Schooltown_Follies",
        "Songs_of_the_Dark_Lantern",
        "Mad_Love",
        "Lullaby_in_Frogland",
        "The_Ringing_of_the_Bell",
        "Babes_in_the_Woods",
        "Into_the_Unknown",
        "The_Unknown",
      ]
    }

    export const episodeTitles_adventuretime = {
      1: [
        "Slumber_Party_Panic",
        "Trouble_in_Lumpy_Space",
        "Prisoners_of_Love",
        "Tree_Trunks",
        "The_Enchiridion!",
        "The_Jiggler",
        "Ricardio_the_Heart_Guy",
        "Business_Time",
        "My_Two_Favorite_People",
        "Memories_of_Boom_Boom_Mountain",
        "Wizard",
        "Evicted",
        "City_of_Thieves",
        "The_Witch's_Garden",
        "What_is_Life",
        "Ocean_of_Fear",
        "When_Wedding_Bells_Thaw",
        "Dungeon",
        "The_Duke",
        "Freak_City",
        "Donny",
        "Henchman",
        "Rainy_Day_Daydream",
        "Whah_Have_You_Done",
        "His_Hero",
        "Gut_Grinder",
      ],

      2: [
        "It_Came_from_the_Nightosphere",
        "The_Eyes",
        "Loyalty_to_the_King",
        "Blood_Under_the_Skin",
        "Storytelling",
        "Slow_Love",
        "Power_Animal",
        "Crystals_Have_Power",
        "The_Other_Tarts",
        "To_Cut_a_Womans_Hair",
        "The_Chamber_of_Frozen_Blades",
        "Her_Parents",
        "The_Pods",
        "The_Silent_King",
        "The_Real_You",
        "Guardians_of_Sunshine",
        "Death_in_Bloom",
        "Susan_Strong",
        "Mystery_Train",
        "Go_With_Me",
        "Belly_of_the_Beast",
        "The_Limit",
        "Video_Makers",
        "Mortal_Folly",
        "Mortal_Recoil",
        "Heat_Signature",
      ],

      3: [
        "Conquest_of_Cuteness",
        "Morituri_te_Salutamus",
        "Memory_of_a_Memory",
        "Hitman",
        "Too_Young",
        "The_Monster",
        "Still",
        "Wizard_Battle",
        "Fionna_and_Cake",
        "What_Was_Missing",
        "Apple_Thief",
        "The_Creeps",
        "From_Bad_to_Worse",
        "Beautopia",
        "No_One_Can_Hear_You",
        "Jake_vs_Me_Mow",
        "Thank_You",
        "The_New_Frontier",
        "Holly_Jolly_Secrets",
        "Holly_Jolly_Secrets_2",
        "Marcelines_Closet",
        "Paper_Pete",
        "Another_Way",
        "Ghost_Princess",
        "Dads_Dungeon",
        "Incendium",
      ],

      4: [
        "Hot_to_the_Touch",
        "Five_Short_Graybles",
        "Web_Weirdos",
        "Dream_of_Love",
        "Return_to_the_Nightosphere",
        "Daddys_Little_Monster",
        "In_Your_Footsteps",
        "Hug_Wolf",
        "Princess_Monster_Wife",
        "Goliad",
        "Beyond_This_Earthly_Realm",
        "Gotcha",
        "Princess_Cookie",
        "Card_Wars",
        "Sons_of_Mars",
        "Burning_Low",
        "BMO_Noire",
        "King_Worm",
        "Lady_Peebles",
        "You_Made_Me",
        "Who_Would_Win",
        "Ignition_Point",
        "The_Hard_Easy",
        "Reign_of_Gunters",
        "I_Remember_You",
        "The_Lich",
      ],

      5: [
        "Finn_the_Human",
        "Jake_the_Dog",
        "Five_More_Short_Graybles",
        "Up_a_Tree",
        "All_the_Little_People",
        "Jake_the_Dad",
        "Davey",
        "Mystery_Dungeon",
        "All_Your_Fault",
        "Little_Dude",
        "Bad_Little_Boy",
        "Vault_of_Bones",
        "The_Great_Bird_Man",
        "Simon_&_Marcy",
        "A_Glitch_Is_a_Glitch",
        "Puhoy",
        "BMO_Lost",
        "Princess_Potluck",
        "James_Baxter_the_Horse",
        "Shh",
        "The_Suitor",
        "The_Partys_Over_Isla_de_Senorita",
        "One_Last_Job",
        "Another_Five_More_Short_Graybles",
        "Candy_Streets",
        "Wizards_Only_Fools",
        "Jake_Suit",
        "Be_More",
        "Sky_Witch",
        "Frost_&_Fire",
        "Too_Old",
        "Earth_&_Water",
        "Time_Sandwich",
        "The_Vault",
        "Love_Games",
        "Dungeon_Train",
        "The_Box_Prince",
        "Red_Starved",
        "We_Fixed_a_Truck",
        "Play_Date",
        "The_Pit",
        "James",
        "Root_Beer_Guy",
        "Apple_Wedding",
        "Blade_of_Grass",
        "Rattleballs",
        "The_Red_Throne",
        "Betty",
        "Bad_Timing",
        "Lemonhope_part_1",
        "Lemonhope_part_2",
        "Billys_Bucket_List",
      ],

      6: [
        "Wake_Up",
        "Escape_From_the_Citadel",
        "James_II",
        "The_Tower",
        "Sad_Face",
        "Breezy",
        "Food_Chain",
        "Furniture_&_Meat",
        "The_Prince_Who_Wanted_Everything",
        "Something_Big",
        "Little_Brother",
        "Ocarina",
        "Thanks_for_the_Crabapples_Giuseppe",
        "Princess_Day",
        "Nemesis",
        "Joshua_&_Margaret_Investigations",
        "Ghost_Fly",
        "Everythings_Jake",
        "Is_That_You",
        "Jake_the_Brick",
        "Dentist",
        "The_Cooler",
        "The_Pajama_War",
        "Evergreen",
        "Astral_Plane",
        "Gold_Stars",
        "The_Visitor",
        "The_Mountain",
        "Dark_Purple",
        "The_Diary",
        "Walnuts_and_Rain",
        "Friends_Forever",
        "Jermaine",
        "Chips_and_Ice_Cream",
        "Graybles_1000_Plus",
        "Hoots",
        "Water_Park_Prank",
        "You_Forgot_Your_Floaties",
        "Be_Sweet",
        "Orgalorg",
        "On_the_Lam",
        "Hot_Diggity_Doom",
        "The_Comet",
      ],

      7: [
        "Bonnie_and_Neddy",
        "Varmints",
        "Cherry_Cream_Soda",
        "Mama_Said",
        "Football",
        "Marceline_the_Vampire_Queen",
        "Everything_Stays",
        "Vamps_About",
        "The_Empress_Eyes",
        "May_I_Come_In",
        "Take_Her_Back",
        "Checkmate",
        "The_Dark_Cloud",
        "The_More_You_Moe_The_More_You_Know",
        "Summer_Showers",
        "Angel_Face",
        "President_Porpoise_is_Missing",
        "Blank_Eyed_Girl",
        "Bad_Jubies",
        "Kings_Ransom",
        "Scamps",
        "Crossover",
        "The_Hall_of_Egress",
        "Flute_Spell",
        "The_Thin_Yellow_Line",
      ],

      8: [
        "Broke_His_Crown",
        "Dont_Look",
        "Beyond_the_Grotto",
        "Lady_Rainicorn_of_the_Crystal_Dimension",
        "I_Am_a_Sword",
        "Bun_Bun",
        "Normal_Man",
        "Elemental",
        "Five_Short_Tables",
        "The_Music_Hole",
        "Daddy_Daughter_Card_Wars",
        "Preboot",
        "Reboot",
        "Two_Swords",
        "Do_No_Harm",
        "Wheels",
        "High_Strangeness",
        "Horse_and_Ball",
        "Jelly_Beans_Have_Power",
        "The_Invitation",
        "Whipple_the_Happy_Dragon",
        "Mysterious_Island",
        "Imaginary_Resources",
        "Hide_and_Seek",
        "Min_&_Marty",
        "Helpers",
        "The_Light_Cloud",
      ],

      9: [
        "Orb",
        "Skyhooks",
        "Bespoken_For",
        "Winter_Light",
        "Cloudy",
        "Slime_Central",
        "Happy_Warrior",
        "Hero_Heart",
        "Skyhooks_II",
        "Abstract",
        "Ketchup",
        "Fionna_and_Cake_and_Fionna",
        "Whispers",
        "Three_Buckets",
      ],

      10: [
        "The_Wild_Hunt",
        "Always_BMO_Closing",
        "Son_of_Rap_Bear",
        "Bonnibel_Bubblegum",
        "Seventeen",
        "Ring_of_Fire",
        "Marcy_&_Hunson",
        "The_First_Investigation",
        "Blenanas",
        "Jake_the_Starchild",
        "Temple_of_Mars",
        "Gumbaldia",
        "Come_Along_With_Me"
      ]
    }

    export const episodeTitles_neongenesis = {
      1: [
        "Angel_Attack",
        "The_Beast",
        "A_Transfer",
        "Hedgehogs_Dilemma",
        "Rei_I",
        "Rei_II",
        "A_Human_Work",
        "Asuka_Strikes!",
        "Both_of_You_Dance_Like_You_Want_to_Win!",
        "Magma_Diver",
        "The_Day_Tokyo3_Stood_Still",
        "She_said_Dont_make_others_suffer_for_your_personal_hatred",
        "Lilliputian_Hitcher",
        "Weaving_a_Story",
        "Those_Women_Longed_For_the_Touch_of_Others_Lips_and_Thus_Invited_Their_Kisses",
        "Splitting_of_the_Breast",
        "Fourth_CHILD",
        "Ambivalence",
        "Introjection",
        "Weaving_a_Story_2_Oral_Stage",
        "He_Was_Aware_That_He_Still_Was_a_Child",
        "Dont_Be",
        "Rei_III",
        "The_Beginning_and_the_End_or_Knockin_on_Heavens_Door",
        "Do_You_Love_Me",
        "Take_Care_of_Yourself"
      ]
    }    

    export const episodeTitles_mobpsycho = {
      1: [
        "Self_Proclaimed_Psychic_Reigen_Arataka_And_Mob",
        "Doubts_About_Youth_The_Telepathy_Club_Appears",
        "An_Invite_to_a_Meeting_Simply_Put_I_Just_Want_to_Be_Popular",
        "Idiots_Only_Event_Kin",
        "Ochimusha_Psychic_Powers_and_Me",
        "Discord_To_Become_One",
        "Exaltation_I've_Obtained_Loss",
        "The_Older_Brother_Bows_Destructive_Intent",
        "Claw_7th_Division",
        "The_Heinous_Aura_Mastermind",
        "Master_Leader",
        "Mob_and_Reigen_A_Giant_Tsuchinoko_Appears"
      ],

      2: [
        "Ripped_Apart_Someone_Is_Watching",
        "Urban_Legends_Encountering_Rumors",
        "One_Danger_After_Another_Degeneration",
        "Inside_Evil_Spirit",
        "Discord_Choices",
        "Poor_Lonely_Whitey",
        "Cornered_True_Identity",
        "Even_Then_Continue_Forward",
        "Show_Me_What_You've_Got_Band_Together",
        "Collision_Power_Type",
        "Guidance_Psychic_Sensor",
        "The_Battle_for_Social_Rehabilitation_Friendship",
        "Boss_Fight_The_Final_Light"
      ],

      3: [
        "Future_Career_Paths",
        "Yokai_Hunter_Amakusa_Haruki_Appears_The_Threat_of_a_Hundred_Demons",
        "Getting_Carried_Away_100",
        "Divine_Tree_1_The_Founder_Appears",
        "Divine_Tree_2_Peace",
        "Divine_Tree_3_Dimple_Is",
        "Transmission_1_Winter_Break",
        "Transmission_2_Encountering_the_Unknown",
        "Mob_1_Moving",
        "Mob_2_Rival",
        "Mob_3_Trauma",
        "Confession_The_Future"
      ]
    } 

    export const episodeTitles_fmab = {
      1: [
        "Fullmetal_Alchemist",
        "The_First_Day",
        "City_of_Heresy",
        "An_Alchemists_Anguish",
        "Rain_of_Sorrows",
        "Road_of_Hope",
        "Hidden_Truths",
        "The_Fifth_Laboratory",
        "Created_Feelings",
        "Separate_Destinations",
        "Miracle_at_Rush_Valley",
        "One_is_All_All_is_One",
        "Beasts_of_Dublith"
      ],

      2: [
        "Those_Who_Lurk_Underground",
        "Envoy_From_the_East",
        "Footsteps_of_a_Comrade_in_Arms",
        "Cold_Flame",
        "The_Arrogant_Palm_of_a_Small_Human",
        "Death_of_the_Undying",
        "Father_Before_the_Grave",
        "Advance_of_the_Fool",
        "Backs_in_the_Distance",
        "Girl_on_the_Battlefield",
        "Inside_the_Belly",
        "Doorway_of_Darkness",
        "Reunion"
      ],
      
      3: [
        "Interlude_Party",
        "Father",
        "Struggle_of_the_Fool",
        "The_Ishvalan_War_of_Extermination",
        "The_520_Cens_Promise",
        "The_Fuhrers_Son",
        "The_Northern_Wall_of_Briggs",
        "Ice_Queen",
        "The_Shape_of_This_Country",
        "Family_Portrait",
        "The_First_Homunculus",
        "Conflict_at_Baschool",
        "Daydream"
      ],

      4: [
        "Homunculus",
        "The_Abyss",
        "Signs_of_a_Counteroffensive",
        "Bite_of_the_Ant",
        "Revving_at_Full_Throttle",
        "The_Promised_Day",
        "Looming_Shadows",
        "Emissary_of_Darkness",
        "The_Oath_in_the_Tunnel",
        "Filial_Affection",
        "Upheaval_in_Central",
        "The_Immortal_Legion",
        "Combined_Strength"
      ],

      5: [
        "Flame_of_Vengeance",
        "Beyond_the_Inferno",
        "The_Adults_Way_of_Life",
        "The_Return_of_the_Fuhrer",
        "Eternal_Leave",
        "Sacrifices",
        "Lost_Light",
        "Eye_of_Heaven_Gateway_of_Earth",
        "He_Who_Would_Swallow_God",
        "A_Fierce_Counterattack",
        "The_Other_Side_of_the_Gateway",
        "Journeys_End"
      ]                  
    }   


    export const episodeTitles_jjk = {
      1: [
        "Ryomen_Sukuna",
        "For_Myself",
        "Girl_of_Steel",
        "Curse_Womb_Must_Die_I",
        "Curse_Womb_Must_Die_II",
        "After_Rain",
        "Assault",
        "Boredom",
        "Small_Fry_and_Reverse_Retribution",
        "Idle_Transfiguration",
        "Narrow-minded",
        "To_You_Someday",
        "Tomorrow",
        "Kyoto_Sister_School_Exchange_Event_Group_Battle_0",
        "Kyoto_Sister_School_Exchange_Event_Group_Battle_1",
        "Kyoto_Sister_School_Exchange_Event_Group_Battle_2",
        "Kyoto_Sister_School_Exchange_Event_Group_Battle_3",
        "Sage",
        "Black_Flash",
        "Nonstandard",
        "Jujutsu_Koshien",
        "The_Origin_of_Blind_Obedience",
        "The_Origin_of_Blind_Obedience_2",
        "Accomplices"
      ],

      2: [
        "Hidden_Inventory",
        "Hidden_Inventory_Part_2",
        "Hidden_Inventory_Part_3",
        "Hidden_Inventory_Part_4",
        "Premature_Death",
        "Its_Like_That",
        "Evening_Festival",
        "The_Shibuya_Incident",
        "The_Shibuya_Incident_Gate_Open",
        "Pandemonium",
        "Summon",
        "Dull_Knife",
        "Red_Scale",
        "Fluctuations",
        "Fluctuations_Part_2",
        "Thunderclap",
        "Thunderclap_Part_2",
        "Right_and_Wrong",
        "Right_and_Wrong_Part_2",
        "Right_and_Wrong_Part_3",
        "Transformation",
        "Transformation_Part_2",
        "The_Shibuya_Incident_Gate_Closed"        
      ],
      3: [
        "Execution",
        "One_More_Time",
        "About_the_Culling_Game",
        "Perfect_Preparation",
        "Fever",
        "Cog",
        "Tokyo_Colony_No_1",
      ]
    }    

    export const episodeTitles_cyberpunk = {
      1: [
        "Let_You_Down",
        "Like_A_Boy",
        "Smooth_Criminal",
        "Lucky_You",
        "All_Eyez_On_Me",
        "Girl_on_Fire",
        "Stronger",
        "Stay",
        "Humanity",
        "My_Moon_My_Man"
      ]
    } 
    
      export const episodeTitles_lovedeathandrobots = {
      1: [
        "Sonnies_Edge",
        "Three_Robots",
        "The_Witness",
        "Suits",
        "Sucker_of_Souls",
        "When_The_Yogurt_Took_Over", 
        "Beyond_the_Aquila_Rift",
        "Good_Hunting",
        "The_Dump",
        "Shapeshifters",
        "Helping_Hand",
        "Fish_Night",
        "Lucky_13",
        "Zima_Blue",
        "Blindspot",
        "Ice_Age",
        "Alternate_Histories",
        "Secret_War",
      ],
      2: [
        "Automated_Customer_Service",
        "Ice",
        "Pop_Squad",
        "Snow_in_the_Desert",
        "The_Tall_Grass",
        "All_Through_the_House",
        "Life_Hutch",
        "The_Drowned_Giant",
      ],
      3: [
        "Three_Robots_Exit_Strategies",
        "Bad_Travelling",
        "The_Very_Pulse_of_the_Machine",
        "Night_of_the_Mini_Dead",
        "Kill_Team_Kill",
        "Swarm",
        "Masons_Rats",
        "In_Vaulted_Halls_Entombed",
        "Jibaro",
      ],
      4: [
        "Close_Encounters_of_the_Mini_Kind",
        "Spider_Rose",
        "How_Zeke_Got_Religion",
        "The_Other_Large_Thing",
        "400_Boys",
        "The_Screaming_of_the_Tyrannosaur",
        "Golgotha",
        "For_He_Can_Creep",
        "Smart_Appliances_Stupid_Owners",
        "Cant_Stop"
      ]
    }    

     export const episodeTitles_blackmirror = {
      1: [
        "The_National_Anthem",
        "Fifteen_Million_Merits",
        "The_Entire_History_of_You",
      ],
      2: [
        "Be_Right_Back",
        "White_Bear",
        "The_Waldo_Moment",
        "White_Christmas",
      ],
      3: [
        "Nosedive",
        "Playtest",
        "Shut_Up_and_Dance",
        "San_Junipero",
        "Men_Against_Fire",
        "Hated_in_the_Nation",
      ],
      4: [
        "USS_Callister",
        "Arkangel",
        "Crocodile",
        "Hang_the_DJ",
        "Metalhead",
        "Black_Museum"
      ],
      5: [
        "Striking_Vipers",
        "Smithereens",
        "Rachel_Jack_and_Ashley_Too"
      ],
      6: [
        "Joan_Is_Awful",
        "Loch_Henry",
        "Beyond_the_Sea",
        "Mazey_Day",
        "Demon_79",
      ],
      7: [
        "Common_People",
        "Bête_Noire",
        "Hotel_Reverie",
        "Plaything",
        "Eulogy",
        "USS_Callister_Into_Infinity",
      ]
    } 

    export const episodeTitles_severance = {
      1: [
        "Good_News_About_Hell",
        "Half_Loop",
        "In_Perpetuity",
        "The_You_You_Are",
        "The_Grim_Barbarity_of_Optics_and_Design",
        "Hide_and_Seek",
        "Defiant_Jazz",
        "Whats_for_Dinner?",
        "The_We_We_Are"
      ],
      2: [
        "Hello_Ms_Cobel",
        "Goodbye_Mrs_Selvig",
        "Who_is_Alive",
        "Woes_Hollow",
        "Trojans_Horse",
        "Attila",
        "Chikhai_Bardo",
        "Sweet_Vitriol",
        "The_After_Hours",
        "Cold_Harbor"
      ],
    } 

    export const episodeTitles_pluribus = {
      1: [
        "We_Is_Us",
        "Pirate_Lady",
        "Grenade",
        "Please_Carol",
        "Got_Milk",
        "HDP",
        "The_Gap",
        "Charm_Offensive",
        "La_Chica_o_El_Mundo"
      ],
    } 
 
    export const episodeTitles_itsalwayssunny = {
      1: [
        "The_Gang_Gets_Racist",
        "Charlie_Wants_an_Abortion",
        "Underage_Drinking_A_National_Concern",
        "Charlie_Has_Cancer",
        "Gun_Fever",
        "The_Gang_Finds_a_Dead_Guy",
        "Charlie_Got_Molested",
      ],
      2: [
        "Charlie_Gets_Crippled",
        "The_Gang_Goes_Jihad",
        "Dennis_And_Dee_Go_On_Welfare",
        "Mac_Bangs_Dennis_Mom",
        "Hundred_Dollar_Baby",
        "The_Gang_Gives_Back",
        "The_Gang_Exploits_a_Miracle",
        "The_Gang_Runs_For_Office",
        "Charlie_Goes_America_All_Over_Everybodys_Ass",
        "Dennis_and_Dee_Get_a_New_Dad",
      ],
      3: [
        "The_Gang_Finds_a_Dumpster_Baby",
        "The_Gang_Gets_Invincible",
        "Dennis_And_Dees_Mom_Is_Dead",
        "The_Gang_Gets_Held_Hostage",
        "The_Aluminum_Monster_vs_Fatty_Magoo",
        "The_Gang_Solves_the_North_Korea_Situation",
        "The_Gang_Sells_Out",
        "Frank_Sets_Sweet_Dee_on_Fire",
        "Sweet_Dees_Dating_a_Retarded_Person",
        "Mac_Is_a_Serial_Killer",
        "Dennis_Looks_Like_a_Registered_Sex_Offender",
        "The_Gang_Gets_Whacked_Part_1",
        "The_Gang_Gets_Whacked_Part_2",
        "Bums_Making_a_Mess_All_Over_the_City",
        "The_Gang_Dances_Their_Asses_Off"
      ],
      4: [
        "Mac_and_Dennis_Manhunters",
        "The_Gang_Solves_the_Gas_Crisis",
        "Americas_Next_Top_Paddys_Billboard_Model_Contest",
        "Macs_Banging_the_Waitress",
        "Mac_&_Charlie_Die_Part_1",
        "Mac_&_Charlie_Die_Part_2",
        "Who_Pooped_the_Bed",
        "Paddys_Pub_The_Worst_Bar_in_Philadelphia",
        "Dennis_Reynolds_An_Erotic_Life",
        "Sweet_Dee_Has_a_Heart_Attack",
        "The_Gang_Cracks_the_Liberty_Bell",
        "The_Gang_Gets_Extreme_Home_Makeover_Edition",
        "The_Nightman_Cometh"
      ],
      5: [
        "The_Gang_Exploits_the_Mortgage_Crisis",
        "The_Gang_Hits_the_Road",
        "The_Great_Recession",
        "The_Gang_Gives_Frank_an_Intervention",
        "The_Waitress_Is_Getting_Married",
        "The_World_Series_Defense",
        "The_Gang_Wrestles_for_the_Troops",
        "Paddys_Pub_Home_of_the_Original_Kitten_Mittens",
        "Mac_and_Dennis_Break_Up",
        "The_DENNIS_System",
        "Mac_and_Charlie_Write_a_Movie",
        "The_Gang_Reignites_the_Rivalry"
      ],
      6: [
        "Mac_Fights_Gay_Marriage",
        "Dennis_Gets_Divorced",
        "The_Gang_Buys_A_Boat",
        "Macs_Big_Break",
        "Mac_And_Charlie_White_Trash",
        "Macs_Mom_Burns_Her_House_Down",
        "Who_Got_Dee_Pregnant",
        "The_Gang_Gets_A_New_Member",
        "Dee_Reynolds_Shaping_Americas_Youth",
        "Charlie_Kelly_King_of_the_Rats",
        "The_Gang_Gets_Stranded_in_the_Woods",
        "Dee_Gives_Birth",
        "A_Very_Sunny_Christmas"
      ],
      7: [
        "Franks_Pretty_Woman",
        "The_Gang_Goes_to_the_Jersey_Shore",
        "Frank_Reynolds_Little_Beauties",
        "Sweet_Dee_Gets_Audited",
        "Franks_Brother",
        "The_Storm_of_the_Century",
        "Chardee_MacDennis_The_Game_of_Games",
        "The_ANTI_Social_Network",
        "The_Gang_Gets_Trapped",
        "How_Mac_Got_Fat",
        "Thunder_Gun_Express",
        "The_High_School_Reunion",
        "The_High_School_Reunion_Part_2_The_Gangs_Revenge"
      ],
      8: [
        "Pop_Pop_The_Final_Solution",
        "The_Gang_Recycles_Their_Trash",
        "The_Maureen_Ponderosa_Wedding_Massacre",
        "Charlie_and_Dee_Find_Love",
        "The_Gang_Gets_Analyzed",
        "Charlies_Mom_Has_Cancer",
        "Franks_Back_in_Business",
        "Charlie_Rules_The_World",
        "The_Gang_Dines_Out",
        "Reynolds_vs_Reynolds_The_Cereal_Defense"
      ],
      9: [
        "The_Gang_Broke_Dee",
        "Gun_Fever_Too_Still_Hot",
        "The_Gang_Tries_Desperately_to_Win_an_Award",
        "Mac_and_Dennis_Buy_a_Timeshare",
        "Mac_Day",
        "The_Gang_Saves_the_Day",
        "The_Gang_Gets_Quarantined",
        "Flowers_for_Charlie",
        "The_Gang_Makes_Lethal_Weapon_6",
        "The_Gang_Squashes_Their_Beefs"
      ],
      10: [
        "The_Gang_Beats_Boggs",
        "The_Gang_Group_Dates",
        "Psycho_Pete_Returns",
        "Charlie_Work",
        "The_Gang_Spies_Like_US",
        "The_Gang_Misses_the_Boat",
        "Mac_Kills_His_Dad",
        "The_Gang_Goes_on_Family_Fight",
        "Frank_Retires",
        "Ass_Kickers_United_Mac_and_Charlie_Join_a_Cult"
      ],
      11: [
        "Chardee_MacDennis_2_Electric_Boogaloo",
        "Frank_Falls_Out_the_Window",
        "The_Gang_Hits_the_Slopes",
        "Dee_Made_A_Smut_Film",
        "Mac_&_Dennis_Move_To_The_Suburbs",
        "Being_Frank",
        "McPoyle_vs_Ponderosa_The_Trial_of_the_Century",
        "Charlie_Catches_a_Leprechaun",
        "The_Gang_Goes_to_Hell",
        "The_Gang_Goes_to_Hell_Part_Two"
      ],
      12: [
        "The_Gang_Turns_Black",
        "The_Gang_Goes_to_a_Water_Park",
        "Old_Lady_House_A_Situation_Comedy",
        "Wolf_Cola_A_Public_Relations_Nightmare",
        "Making_Dennis_Reynolds_a_Murderer",
        "Hero_or_Hate_Crime",
        "PTSDee",
        "The_Gang_Tends_Bar",
        "A_Crickets_Tale",
        "Dennis_Double_Life"
      ],
      13: [
        "The_Gang_Makes_Paddys_Great_Again",
        "The_Gang_Escapes",
        "The_Gang_Beats_Boggs_Ladies_Reboot",
        "Times_Up_for_the_Gang",
        "The_Gang_Gets_New_Wheels",
        "The_Gang_Solves_the_Bathroom_Problem",
        "The_Gang_Does_a_Clip_Show",
        "Charlies_Home_Alone",
        "The_Gang_Wins_the_Big_Game",
        "Mac_Finds_His_Pride"
      ],
      14: [
        "The_Gang_Gets_Romantic",
        "Thunder_Gun_4_Maximum_Cool",
        "Dee_Day",
        "The_Gang_Chokes",
        "The_Gang_Texts",
        "The_Janitor_Always_Mops_Twice",
        "The_Gang_Solves_Global_Warming",
        "Paddys_Has_a_Jumper",
        "A_Womans_Right_to_Chop",
        "Waiting_for_Big_Mo"
      ],
      15: [
        "2020_A_Year_In_Review",
        "The_Gang_Makes_Lethal_Weapon_7",
        "The_Gang_Buys_a_Roller_Rink",
        "The_Gang_Replaces_Dee_With_a_Monkey",
        "The_Gang_Goes_to_Ireland",
        "The_Gangs_Still_in_Ireland",
        "Dee_Sinks_in_a_Bog",
        "The_Gang_Carries_a_Corpse_Up_a_Mountain"
      ],
      16: [
        "The_Gang_Inflates",
        "Frank_Shoots_Every_Member_of_the_Gang",
        "The_Gang_Gets_Cursed",
        "Frank_vs_Russia",
        "Celebrity_Booze_The_Ultimate_Cash_Grab",
        "Risk_E_Rats_Pizza_&_Amusement_Center",
        "The_Gang_Goes_Bowling",
        "Dennis_Takes_a_Mental_Health_Day",
      ],
      17: [
        "The_Gang_Fucks_Up_Abbott_Elementary",
        "Frank_Is_in_a_Coma",
        "Mac_and_Dennis_Become_EMTs",
        "Thought_Leadership_A_Corporate_Conversation",
        "The_Gang_Goes_to_a_Dog_Track",
        "Overage_Drinking_A_National_Concern",
        "The_Gang_Gets_Ready_for_Prime_Time",
        "The_Golden_Bachelor_Live"
      ]
    }
    
    export const episodeTitles_thetwilightzone = {
      1: [
        "Where_Is_Everybody",
        "One_for_the_Angels",
        "Mr_Denton_on_Doomsday",
        "The_Sixteen_Millimeter_Shrine",
        "Walking_Distance",
        "Escape_Clause",
        "The_Lonely",
        "Time_Enough_at_Last",
        "Perchance_to_Dream",
        "Judgment_Night",
        "And_When_the_Sky_Was_Opened",
        "What_You_Need",
        "The_Four_of_Us_Are_Dying",
        "Third_from_the_Sun",
        "I_Shot_an_Arrow_into_the_Air",
        "The_HitchHiker",
        "The_Fever",
        "The_Last_Flight",
        "The_Purple_Testament",
        "Elegy",
        "Mirror_Image",
        "The_Monsters_Are_Due_on_Maple_Street",
        "A_World_of_Difference",
        "Long_Live_Walter_Jameson",
        "People_Are_Alike_All_Over",
        "Execution",
        "The_Big_Tall_Wish",
        "A_Nice_Place_to_Visit",
        "Nightmare_as_a_Child",
        "A_Stop_at_Willoughby",
        "The_Chaser",
        "A_Passage_for_Trumpet",
        "Mr_Bevis",
        "The_After_Hours",
        "The_Mighty_Casey",
        "A_World_of_His_Own"
      ],
      2: [
        "King_Nine_Will_Not_Return",
        "The_Man_in_the_Bottle",
        "Nervous_Man_in_a_Four_Dollar_Room",
        "A_Thing_About_Machines",
        "The_Howling_Man",
        "Eye_of_the_Beholder",
        "Nick_of_Time",
        "The_Lateness_of_the_Hour",
        "The_Trouble_with_Templeton",
        "A_Most_Unusual_Camera",
        "The_Night_of_the_Meek",
        "Dust",
        "Back_There",
        "The_Whole_Truth",
        "The_Invaders",
        "A_Penny_For_Your_Thoughts",
        "Twenty_Two",
        "The_Odyssey_of_Flight_33",
        "Mr_Dingle_the_Strong",
        "Static",
        "The_Prime_Mover",
        "Long_Distance_Call",
        "A_Hundred_Yards_over_the_Rim",
        "The_Rip_Van_Winkle_Caper",
        "The_Silence",
        "Shadow_Play",
        "The_Mind_and_the_Matter",
        "Will_the_Real_Martian_Please_Stand_Up",
        "The_Obsolete_Man"
      ],
      3: [
        "Two",
        "The_Arrival",
        "The_Shelter",
        "The_Passersby",
        "A_Game_of_Pool",
        "The_Mirror",
        "The_Grave",
        "Its_a_Good_Life",
        "DeathsHead_Revisited",
        "The_Midnight_Sun",
        "Still_Valley",
        "The_Jungle",
        "Once_Upon_a_Time",
        "Characters_in_Search_of_an_Exit",
        "A_Quality_of_Mercy",
        "Nothing_in_the_Dark",
        "One_More_Pallbearer",
        "Dead_Mans_Shoes",
        "The_Hunt",
        "Showdown_with_Rance_McGrew",
        "Kick_the_Can",
        "A_Piano_in_the_House",
        "The_Last_Rites_of_Jeff_Myrtlebank",
        "To_Serve_Man",
        "The_Fugitive",
        "Little_Girl_Lost",
        "Person_or_Persons_Unknown",
        "The_Little_People",
        "Four_OClock",
        "Hocus_Pocus_and_Frisby",
        "The_TradeIns",
        "The_Gift",
        "The_Dummy",
        "Young_Mans_Fancy",
        "I_Sing_the_Body_Electric",
        "Cavender_is_Coming",
        "The_Changing_of_the_Guard"
      ],
      4: [
        "In_His_Image",
        "The_Thirty_Fathom_Grave",
        "Valley_of_the_Shadow",
        "Hes_Alive",
        "Mute",
        "Death_Ship",
        "JessBelle",
        "Miniature",
        "Printers_Devil",
        "No_Time_Like_the_Past",
        "The_Parallel",
        "I_Dream_of_Genie",
        "The_New_Exhibit",
        "Of_Late_I_Think_of_Cliffordville",
        "The_Invisible_World_of_Horace_Ford",
        "On_Thursday_We_Leave_for_Home",
        "Passage_on_the_Lady_Anne",
        "The_Bard"
      ],
      5: [
        "In_Praise_of_Pip",
        "Steel",
        "Nightmare_at_20000_Feet",
        "A_Kind_of_Stopwatch",
        "The_Last_Night_of_a_Jockey",
        "Living_Doll",
        "The_Old_Man_in_the_Cave",
        "Uncle_Simon",
        "Probe_7_Over_and_Out",
        "The_7th_is_Made_Up_of_Phantoms",
        "A_Short_Drink_from_a_Certain_Fountain",
        "Ninety_Years_Without_Slumbering",
        "RingADing_Girl",
        "You_Drive",
        "The_Long_Morrow",
        "The_Self_Improvement_of_Salvadore_Ross",
        "Number_12_Looks_Just_Like_You",
        "Black_Leather_Jackets",
        "Night_Call",
        "From_Agnes_With_Love",
        "Spur_of_the_Moment",
        "An_Occurrence_at_Owl_Creek_Bridge",
        "Queen_of_the_Nile",
        "Whats_in_the_Box",
        "The_Masks",
        "I_Am_the_Night_Color_Me_Black",
        "Sounds_and_Silences",
        "Caesar_and_Me",
        "The_Jeopardy_Room",
        "Stopover_in_a_Quiet_Town",
        "The_Encounter",
        "Mr_Garrity_and_the_Graves",
        "The_Brain_Center_at_Whipples",
        "Come_Wander_With_Me",
        "The_Fear",
        "The_Bewitchin_Pool"
      ]
    } 



    export const allEpisodeTitles = {
      "steven-universe": episodeTitles_stevenuniverse,
      "over-the-garden-wall": episodeTitles_overthegardenwall,
      "adventure-time": episodeTitles_adventuretime,
      "neon-genesis": episodeTitles_neongenesis,
      "mob-psycho": episodeTitles_mobpsycho,
      "fmab": episodeTitles_fmab,
      "jjk": episodeTitles_jjk,
      "cyberpunk": episodeTitles_cyberpunk,
      "lovedeathandrobots": episodeTitles_lovedeathandrobots,
      "blackmirror": episodeTitles_blackmirror,
      "severance": episodeTitles_severance,
      "pluribus": episodeTitles_pluribus,
      "itsalwayssunny": episodeTitles_itsalwayssunny,
      "thetwilightzone": episodeTitles_thetwilightzone,
    };