export const SHOWS = [
    { 
        id: "steven-universe", 
        title: "Steven Universe", 
        creator: "Rebecca Sugar", 
        background: "/images/stevenuniverse/covers/stevenuniverse_backdrop.svg", 
        ratings: "8.2", 
        type: "TV", 
        keyart: "/images/stevenuniverse/covers/stevenuniverseIcon.jpg", 
        card: "/images/cardimages/stevenUniverseLogo1.svg", 
        dateadded: "1-1-25",
    }, 
    
    { 
        id: "adventure-time", 
        title: "Adventure Time", 
        creator: "Pendleton Ward", 
        background: "/images/adventuretime/covers/adventuretime_backdrop.svg", 
        ratings: "8.6", 
        type: "TV", 
        keyart: "/images/adventuretime/covers/adventuretimeIcon.jpg", 
        card: "/images/cardimages/adventuretimeLogo1.svg",
        dateadded: "1-2-25",
    },
    
    { 
        id: "over-the-garden-wall", 
        title: "Over the Garden Wall", 
        creator: "Patrick McHale", 
        background: "/images/overthegardenwall/covers/overthegardenwall_backdrop.svg", 
        ratings: "8.7", 
        type: "TV", 
        keyart: "/images/overthegardenwall/covers/overthegardenwallIcon.jpg", 
        card: "/images/cardimages/otgwLogo1.svg", 
        dateadded: "1-3-25",
    },
        
    { 
        id: "perfect-blue", 
        title: "Perfect Blue", 
        creator: "Satoshi Kon", 
        background: "/images/perfectblue/covers/perfectblue_backdrop.svg", 
        ratings: "8.0", 
        type: "Movies", 
        keyart: "/images/perfectblue/covers/perfectblueIcon.jpg", 
        card: "/images/cardimages/perfectblueLogo.svg", 
        dateadded: "1-4-25",
    },

    { 
        id: "paprika", 
        title: "Paprika", 
        creator: "Satoshi Kon", 
        background: "/images/paprika/covers/paprika_backdrop.svg", 
        ratings: "7.7", 
        type: "Movies", 
        keyart: "/images/paprika/covers/paprikaIcon.jpeg", 
        card: "/images/cardimages/paprikaLogo1.svg", 
        dateadded: "1-5-25",
    },
    
    { 
        id: "princess-mononoke", 
        title: "Princess Mononoke", 
        creator: "Miyazaki", 
        background: "/images/princessmononoke/covers/princessmononoke_backdrop.svg", 
        ratings: "8.3", 
        type: "Movies", 
        keyart: "/images/princessmononoke/covers/princessmononokeIcon.jpg", 
        card: "/images/cardimages/princessLogo1.svg", 
        dateadded: "1-6-25",
    },

    { 
        id: "aniara", 
        title: "Aniara", 
        creator: "Arne Arnbom", 
        background: "/images/aniara/covers/aniara_backdrop.svg", 
        ratings: "5.8", 
        type: "Movies", 
        keyart: "/images/aniara/covers/aniaraLogomobile.jpg",
        card: "/images/cardimages/aniaraLogo.jpg", 
        dateadded: "1-7-25",
    },
    
    { 
        id: "weapons", 
        title: "Weapons", 
        creator: "Zach Cregger", 
        background: "/images/weapons/covers/weapons_backdrop.svg", 
        ratings: "7.6", 
        type: "Movies", 
        keyart: "/images/weapons/covers/weapons_mobileLogo.jpg", 
        card: "/images/cardimages/weaponsLogo.svg", 
        dateadded: "1-8-25",
    },  
    
    { 
        id: "the-vanishing", 
        title: "The Vanishing", 
        creator: "George Sluizer", 
        background: "/images/thevanishing/covers/thevanishing_backdrop.svg", 
        ratings: "7.7", 
        type: "Movies", 
        keyart: "/images/thevanishing/covers/thevanishing_mobileLogo.jpg", 
        card: "/images/cardimages/thevanishingLogo.svg", 
        dateadded: "1-9-25",
    },        
    
    { 
        id: "the-lighthouse", 
        title: "The Lighthouse", 
        creator: "Robert Eggers", 
        background: "/images/thelighthouse/covers/thelighthouse_backdrop.svg", 
        ratings: "7.4", 
        type: "Movies", 
        keyart: "/images/thelighthouse/covers/thelighthouse_mobilelogo.jpg", 
        card: "/images/cardimages/thelighthouseLogo.svg", 
        dateadded: "1-10-25",
    },      
    
    { 
        id: "a-ghost-story", 
        title: "A Ghost Story", 
        creator: "David Lowery", 
        background: "/images/aghoststory/covers/aghoststory_backdrop.svg", 
        ratings: "6.8", 
        type: "Movies", 
        keyart: "/images/aghoststory/covers/aghoststory_mobilelogo.jpg", 
        card: "/images/cardimages/aghoststoryLogo.svg", 
        dateadded: "1-11-25",
    },
        
    
    { 
        id: "little-miss-sunshine", 
        title: "Little Miss Sunshine", 
        creator: "Jonathan Dayton", 
        background: "/images/littlemisssunshine/covers/littlemisssunshine_backdrop.svg", 
        ratings: "7.8", 
        type: "Movies", 
        keyart: "/images/littlemisssunshine/covers/littlemisssunshine_mobilelogo.jpg", 
        card: "/images/cardimages/littlemisssunshineLogo.svg",
        dateadded: "1-12-25", 
    },   

    { 
        id: "ghost-in-the-shell", 
        title: "Ghost in The Shell", 
        creator: "Kôkaku Kidôtai", 
        background: "/images/ghostintheshell/covers/ghostintheshell_backdrop.svg", 
        ratings: "7.9", 
        type: "Movies", 
        keyart: "/images/ghostintheshell/covers/ghostintheshell_mobilelogo.webp", 
        card: "/images/cardimages/ghostintheshellLogo.svg", 
        dateadded: "1-13-25",
    },  
    
    { 
        id: "mob-psycho", 
        title: "Mob Psycho 100", 
        creator: "ONE", 
        background: "/images/mobpsycho/covers/mobpsycho_backdrop.svg", 
        ratings: "8.5", 
        type: "TV", 
        keyart: "/images/mobpsycho/covers/mobpsycho_mobilelogo.jpg", 
        card: "/images/cardimages/mobpsychoLogo.svg",
        dateadded: "1-14-25", 
    }, 

    { 
        id: "fmab", 
        title: "Fullmetal Alchemist", 
        creator: "Bones", 
        background: "/images/fmab/covers/fmab_backdrop.svg", 
        ratings: "9.1", 
        type: "TV", 
        keyart: "/images/fmab/covers/fmab_mobilelogo.jpg", 
        card: "/images/cardimages/fmabLogo.svg", 
        dateadded: "1-15-25",
    },
    
    { 
        id: "neon-genesis", 
        title: "Neon Genesis Evangelion", 
        creator: "Hideaki Ano", 
        background: "/images/neongenesis/covers/neongenesis_backdrop.svg", 
        ratings: "8.5", 
        type: "TV", 
        keyart: "/images/neongenesis/covers/neongenesisIcon.svg", 
        card: "/images/cardimages/neongenesisLogo.svg", 
        dateadded: "1-17-25",
    }, 

    { 
        id: "cyberpunk", 
        title: "Cyberpunk: Edgerunners", 
        creator: "Rafal Jaki", 
        background: "/images/cyberpunk/covers/cyberpunk_backdrop.svg", 
        ratings: "8.3", 
        type: "TV", 
        keyart: "/images/cyberpunk/covers/cyberpunk_mobileLogo.jpg", 
        card: "/images/cardimages/cyberpunkLogo.svg", 
        dateadded: "1-18-25",
    },                     

    { 
        id: "solaris", 
        title: "Solaris", 
        creator: "Andrei Tarkovsky", 
        background: "/images/solaris/covers/solaris_backdrop.svg", 
        ratings: "7.6", 
        type: "Movies", 
        keyart: "/images/solaris/covers/solaris_mobileLogo.jpg", 
        card: "/images/cardimages/solarisLogo.svg", 
        dateadded: "1-19-25",
    },       

    { 
        id: "event-horizon", 
        title: "Event Horizon", 
        creator: "Paul W.S. Anderson", 
        background: "/images/eventhorizon/covers/eventhorizon_backdrop.svg", 
        ratings: "6.6", 
        type: "Movies", 
        keyart: "/images/eventhorizon/covers/eventhorizon_mobileLogo.png", 
        card: "/images/cardimages/eventhorizonLogo.svg", 
        dateadded: "1-20-25",
    },  
    
    { 
        id: "tokyo-godfathers", 
        title: "Tokyo Godfathers", 
        creator: "Satoshi Kon", 
        background: "/images/tokyogodfathers/covers/tokyogodfathers_backdrop.svg", 
        ratings: "7.8",
        type: "Movies", 
        keyart: "/images/tokyogodfathers/covers/tokyogodfathers_mobileLogo.jpg", 
        card: "/images/cardimages/tokyogodfathersLogo.svg", 
        dateadded: "1-21-25",
    },    
    
    { 
        id: "lovedeathandrobots", 
        title: "Love Death + Robots", 
        creator: "David Fincher", 
        background: "/images/lovedeathandrobots/covers/lovedeathandrobots_backdrop.svg", 
        ratings: "8.4", 
        type: "TV", 
        keyart: "/images/lovedeathandrobots/covers/lovedeathandrobots_mobileLogo.png", 
        card: "/images/cardimages/lovedeathandrobotsLogo.svg", 
        dateadded: "1-22-25",
    },      

    { 
        id: "demons", 
        title: "Demons", 
        creator: "Toshio Matsumoto", 
        background: "/images/demons/covers/demons_backdrop.svg", 
        ratings: "7.9", 
        type: "Movies", 
        keyart: "/images/demons/covers/demons_mobileLogo.jpg", 
        card: "/images/cardimages/demonsLogo.svg", 
        dateadded: "1-23-25",
    },    

    { 
        id: "blackmirror", 
        title: "Black Mirror", 
        creator: "Charlie Brooker", 
        background: "/images/blackmirror/covers/blackmirror_backdrop.svg", 
        ratings: "8.7", 
        type: "TV", 
        keyart: "/images/blackmirror/covers/blackmirror_mobileLogo.png", 
        card: "/images/cardimages/blackmirrorLogo.svg", 
        dateadded: "1-24-25",
    },      

    { 
        id: "severance", 
        title: "Severance", 
        creator: "Dan Erickson", 
        background: "/images/severance/covers/severance_backdrop.svg", 
        ratings: "8.7", 
        type: "TV", 
        keyart: "/images/severance/covers/severance_mobileLogo.png", 
        card: "/images/cardimages/severanceLogo.svg",
        dateadded: "1-25-25",
    },      

    {
        id: "pluribus",  
        title: "Pluribus",
        creator: "Dan Erickson", 
        background: "/images/pluribus/covers/pluribus_backdrop.svg", 
        ratings: "8.5", 
        type: "TV", 
        keyart: "/images/pluribus/covers/pluribus_mobileLogo.png", 
        card: "/images/cardimages/pluribusLogo.svg",
        dateadded: "1-26-25",
    },  

    { 
        id: "akira", 
        title: "Akira", 
        creator: "Katsuhiro Ôtomo", 
        background: "/images/akira/covers/akira_backdrop.svg", 
        ratings: "8.0", 
        type: "Movies", 
        keyart: "/images/akira/covers/akira_mobileLogo.png", 
        card: "/images/cardimages/akiraLogo.svg", 
        dateadded: "1-27-25",
    },  

    { 
        id: "exmachina", 
        title: "Ex Machina", 
        creator: "Alex Garland", 
        background: "/images/exmachina/covers/exmachina_backdrop.svg", 
        ratings: "7.7", 
        type: "Movies", 
        keyart: "/images/exmachina/covers/exmachina_mobileLogo.png", 
        card: "/images/cardimages/exmachinaLogo.svg", 
        dateadded: "1-28-25",
    }, 

    { 
        id: "annihilation", 
        title: "Annihilation", 
        creator: "Alex Garland", 
        background: "/images/annihilation/covers/annihilation_backdrop.svg", 
        ratings: "6.8", 
        type: "Movies", 
        keyart: "/images/annihilation/covers/annihilation_mobileLogo.png", 
        card: "/images/cardimages/annihilationLogo.svg", 
        dateadded: "1-29-25",
    }, 

    {
        id: "itsalwayssunny",  
        title: "It's Always Sunny in Philadelphia",
        creator: "Glenn Howerton", 
        background: "/images/itsalwayssunny/covers/itsalwayssunny_backdrop.svg", 
        ratings: "8.8", 
        type: "TV", 
        keyart: "/images/itsalwayssunny/covers/itsalwayssunny_mobileLogo.jpg", 
        card: "/images/cardimages/itsalwayssunnyLogo.svg",
        dateadded: "1-30-25",
    }, 

    {
        id: "thetwilightzone",  
        title: "The Twilight Zone",
        creator: "Rod Serling", 
        background: "/images/thetwilightzone/covers/thetwilightzone_backdrop.svg", 
        ratings: "9.0", 
        type: "TV", 
        keyart: "/images/thetwilightzone/covers/thetwilightzone_mobileLogo.png", 
        card: "/images/cardimages/thetwilightzoneLogo.svg",
        dateadded: "2-1-25",
    }, 

    { 
        id: "redline", 
        title: "Redline", 
        creator: "Takeshi Koike", 
        background: "/images/redline/covers/redline_backdrop.svg", 
        ratings: "7.5", 
        type: "Movies", 
        keyart: "/images/redline/covers/redline_mobileLogo.jpg", 
        card: "/images/cardimages/redlineLogo.svg", 
        dateadded: "2-2-25",
    }, 

    { 
        id: "jjk", 
        title: "Jujutsu Kaisen", 
        creator: "Gege Akutami", 
        background: "/images/jjk/covers/jjk_backdrop.svg", 
        ratings: "8.5", 
        type: "TV", 
        keyart: "/images/jjk/covers/jjk_mobileLogo2.jpg", 
        card: "/images/cardimages/jjkLogo2.svg", 
        dateadded: "2-3-25",
    },     

    { 
        id: "bugonia", 
        title: "Bugonia", 
        creator: "Yorgos Lanthimos", 
        background: "/images/bugonia/covers/bugonia_backdrop.svg", 
        ratings: "7.4", 
        type: "Movies", 
        keyart: "/images/bugonia/covers/bugonia_mobileLogo.jpg", 
        card: "/images/cardimages/bugoniaLogo.svg", 
        dateadded: "2-4-25",
    }, 

    { 
        id: "frankenstein", 
        title: "Frankenstein", 
        creator: "Guillermo del Toro", 
        background: "/images/frankenstein/covers/frankenstein_backdrop.svg", 
        ratings: "7.4", 
        type: "Movies", 
        keyart: "/images/frankenstein/covers/frankenstein_mobileLogo.jpg", 
        card: "/images/cardimages/frankensteinLogo.svg", 
        dateadded: "2-5-25",
    }, 
    
    { 
        id: "truedetective", 
        title: "True Detective", 
        creator: "Nic Pizzolatto", 
        background: "/images/truedetective/covers/truedetective_backdrop.svg", 
        ratings: "8.8", 
        type: "TV", 
        keyart: "/images/truedetective/covers/truedetective_mobileLogo.jpg", 
        card: "/images/cardimages/truedetectiveLogo.svg", 
        dateadded: "2-6-25",
    },

    { 
        id: "sunsetboulevard", 
        title: "Sunset Boulevard", 
        creator: "Billy Wilder", 
        background: "/images/sunsetboulevard/covers/sunsetboulevard_backdrop.svg", 
        ratings: "8.4", 
        type: "Movies", 
        keyart: "/images/sunsetboulevard/covers/sunsetboulevard_mobileLogo.jpg", 
        card: "/images/cardimages/sunsetboulevardLogo.svg", 
        dateadded: "2-7-25",
    },     

    {
        id: "shikijitsu",
        title: "Shiki-Jitsu",
        creator: "Hideaki Anno", 
        background: "/images/shikijitsu/covers/shikijitsu_backdrop.svg",
        ratings: "7.5",
        type: "Movies",
        keyart: "/images/shikijitsu/covers/shikijitsu_mobileLogo.jpg", 
        card: "/images/cardimages/shikijitsuLogo.svg", 
        dateadded: "2-8-25",
    },

    {
        id: "speaknoevil",
        title: "Speak No Evil",
        creator: "Christian Tafdrup", 
        background: "/images/speaknoevil/covers/speaknoevil_backdrop.svg",
        ratings: "6.7",
        type: "Movies",
        keyart: "/images/speaknoevil/covers/speaknoevil_mobileLogo.jpg", 
        card: "/images/cardimages/speaknoevilLogo.svg", 
        dateadded: "2-9-25",
    },

    {
        id: "ikiru",
        title: "Ikiru",
        creator: "Akira Kurosawa", 
        background: "/images/ikiru/covers/ikiru_backdrop.svg",
        ratings: "8.3",
        type: "Movies",
        keyart: "/images/ikiru/covers/ikiru_mobileLogo.jpg", 
        card: "/images/cardimages/ikiruLogo.svg", 
        dateadded: "2-10-25",
    },

    {
        id: "theericandreshow",
        title: "The Eric Andre Show",
        creator: "Eric André", 
        background: "/images/theericandreshow/covers/theericandreshow_backdrop.svg",
        ratings: "8.5",
        type: "TV",
        keyart: "/images/theericandreshow/covers/theericandreshow_mobileLogo.jpg", 
        card: "/images/cardimages/theericandreshowLogo.svg", 
        dateadded: "2-11-25",
    },    

    {
        id: "pokemon2000",
        title: "Pokémon 2000",
        creator: "Kunihiko Yuyama", 
        background: "/images/pokemon2000/covers/pokemon2000_backdrop.svg",
        ratings: "6.1",
        type: "Movies",
        keyart: "/images/pokemon2000/covers/pokemon2000_mobileLogo.jpg", 
        card: "/images/cardimages/pokemon2000Logo.svg", 
        dateadded: "2-12-25",
    }, 

    {
        id: "coherence",
        title: "Coherence",
        creator: "James Ward Byrkit", 
        background: "/images/coherence/covers/coherence_backdrop.svg",
        ratings: "7.2",
        type: "Movies",
        keyart: "/images/coherence/covers/coherence_mobileLogo.jpg", 
        card: "/images/cardimages/coherenceLogo.svg", 
        dateadded: "2-13-25",
    }, 

    {
        id: "exit8",
        title: "Exit 8",
        creator: "Genki Kawamura", 
        background: "/images/exit8/covers/exit8_backdrop.svg",
        ratings: "6.4",
        type: "Movies",
        keyart: "/images/exit8/covers/exit8_mobileLogo.jpg", 
        card: "/images/cardimages/exit8Logo.svg", 
        dateadded: "2-14-25",
    }, 
];